### ISSUE TITLE
Outbound Message Validate - Suppress Retry Bug for an invalid phone number

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/gambit-conversations#290]
_BUG_
-------------------
#### Current Behavior

A string is returned in `helpers.formatMobileNumber` for User [5a8c855fa0bfad090c480e86](https://aurora.dosomething.org/users/5a8c855fa0bfad090c480e86), so the Validate Outbound Message isn't returning a 422. When we attempt to post this message to Twilio via `req.conversation.postLastOutboundMessageToPlatform()`, an error is returned but we're not suppressing retries, causing Blink to retry the message over and over.
The user's phone number contains 11 digits (not including `+1` prefix) instead of the expected 10.

> The 'To' number [removed] is not a valid phone number

#### Desired Behavior
The Validate Outbound Message middleware should have returned a 422 for this User ID.

#### Steps to Replicate
Post a Signup message for User `5a8c855fa0bfad090c480e86` (please make sure we didn't fix their profile though if you're going to do this)

#### Why This Matters
Unnecessary Blink retries == Unnecessary stress!

**Comment by aaronschachter** [comment]
This is the corresponding Thor User: 5a8c886b10707d0bde51084b, which i created by testing their number against staging

**Comment by rapala61** [comment]
@aaronschachter  I'm looking into this a little closer since I found 5 requests caught in the retry loop. My hunch is that this change in https://github.com/DoSomething/gambit-conversations/pull/288/files#diff-e33df83682f212a849fb570643a82748L312 unplugged our ears and we are now responding with errors where before we were just logging the error.
