### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/gambit-conversations#38]
Doesn't exist yet

**Comment by rapala61** [comment]
## Summary
Add authentication middleware to `receive-message` route.

## Story
- [ ] As an O'Dev I want to send POST requests with Basic Auth name and password to the `receive-message` endpoint, in order to secure the endpoint from unauthorized POST requests.

## Done
- [ ] The endpoint should respond with a `403` forbidden error when receiving unauthorized requests.
- [ ] The endpoint should not respond with a `403` error if the valid name and password are sent with the request.
