### ISSUE TITLE
Inbound, Outbound Message + Blink retries

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/gambit-conversations#51]
Once Blink starts retrying Conversations API requests that fail -- we should not create additional inbound/outbound Message documents for each retry.

**Comment by rapala61** [comment]
I'm starting to work on this task. There are a few ways I can think about to add this feature. This is the one I think would be the most practical to apply:

# Add a `metadata` property to the `Message` model to track the `requestId`.
Each `Message` would have this `metadata` object property which would contain the `requestId` number that created it.

### Use case
> We would track the retry count in`req.retryCount`.
> We would track the request id in `req.requestId`.

##### Failed Request
1. Request with id `12345` comes in through `receive-message`.
1. It creates a new conversation since none was found for this `platformUserId`.
1. A new inbound message is created with a metadata object that includes the `requestId`.
1. At some point in the code, a 500 occurs in the app or as a response to a 3rd party request from the app.
1. Blink will get this error response, will retry.

##### Retried Request
1. If the `retryCount` is more than `0`. Instead of creating a message, inspect that there is no other message in this user's conversation that matches this requestId.
1. If there is a message. Load it and save retry count. If not, create it.

### Tradeoffs
- (-/+) Relying completely on blink to prevent duplicate messages.
- (-) Each retry will trigger a DB lookup. Maybe indexing this field would help. We definitely need to index Conversation's `platformUserId` if its not already.

Let me know if this makes sense or if you have other suggestions on how to implement this! @DFurnes @aaronschachter @sergii-tkachenko

**Comment by rapala61** [comment]
Reviving this convo. @sergii-tkachenko @aaronschachter how do we feel about the approach I explain above?

**Comment by aaronschachter** [comment]
This makes sense to me. 2 questions come to mind --

* For:
> Relying completely on blink to prevent duplicate messages.
Do you mean specifically relying on Blink's `retryCount` ? Do we have any other options?

* For `message.metadata` -- I'm considering pros/cons of an `metadata` property vs creating separate fields. #52 would seem to fit there but then where do we make the call on things like Broadcast Id #56 ?

**Comment by sergii-tkachenko** [comment]
I'm not opposed to having dedicated metadata field on `Message` model similar to one in Blink.

I'm planning to extend Blink's field with additional info besides 'retryCount', for example, user IP or sender app. It could be really useful for debugging. As I see it, Blink can pass the field's content to Gambit with HTTP headers.

**Comment by rapala61** [comment]
This is what I have so far.

![conversations retry handling - user flow](https://user-images.githubusercontent.com/863301/30079926-7aaef5f0-9247-11e7-9944-61ea1f66f41a.png)

**Comment by sergii-tkachenko** [comment]
I'm a little bit confused where the diagram starts.

**Comment by rapala61** [comment]
Starts at the Blink app.

**Comment by rapala61** [comment]
@aaronschachter 
1. I was thinking in the context of needing the `requestId` and `retryCount` headers that come from Blink. If we were to receive inbound from other sources (like while testing), we could loose the dupe protection laid out in this approach. I can't think of an alternative, other than just being liberal with where we look for this info, in the query, body, and headers, so we can easily send them ourselves when testing.
2. It's not super clear to me either, but the way it makes sense to me, is to think of 1st level properties as mission critical to understand and use the resource. #52 and #56 would be 1st level properties of the message object. Metadata would be an object that stores data that is related to the message (or 2nd level), descriptive of the whole operation, rather than mission critical to understand the resource.

**Comment by sergii-tkachenko** [comment]
Looks right to me. One clarification: how's conversation is loaded? By its own `requestId`? Or by checking if it has a message with matching `metadata.requestId`?

**Comment by rapala61** [comment]
@sergii-tkachenko it's loaded by querying conversations based on the `platform` and `platformUserId`. The message, in case that there is a `retryCount` > 0, would be loaded by comparing the `metadada.requestId`.

**Comment by sergii-tkachenko** [comment]
Ah, I see. Thank you for the explanation, @rapala61!
